### ISSUE TITLE
Home page won't load?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/xsimd-feedstock#2]
When I load the homepage ( http://quantstack.net/xsimd ), I see the following. Is the homepage simply not built yet or has it moved?

<img width="1552" alt="screen shot 2017-06-30 at 21 56 26" src="https://user-images.githubusercontent.com/3019665/27758313-fe14a504-5dde-11e7-81c9-7dbd02fb390e.png">

**Comment by SylvainCorlay** [comment]
@jakirkham fixed! I put in a place holder. Thanks.

**Comment by jakirkham** [comment]
Thanks.
