### ISSUE TITLE
Rebuild failing with xsimd 9.0.1 on macOS

### ISSUE THREAD

**Issue by lamyj** [conda-forge/xsimd-feedstock#87]
### Comment:

During the rebuild of one of my packages, the macOS builds failed due to a missing `exp10f`, see [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=600674&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=1146) for the full details.

It seems that xtensor-stack/xsimd#811 fixed this issue, but the PR was merged just after the release of xsimd 9.0.1. Could this PR be backported as a patch in the Conda-forge package?

**Comment by JohanMabille** [comment]
Sorry I totally missed this issue. We released 10.0.0, can you upgrade? If not (for any reason), let me know, I will backport the bugfix.

**Comment by lamyj** [comment]
It works like a charm with 10.0.0, thanks!

@lsoustelle, the issue with Sycomore on macOS is fixed with the latest version of the conda package
